default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    build_app(
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.cybage.alm" => "CybageCI"
        },
        teamID: ENV["DEVELOPER_TEAM_ID"],
        signingStyle: "manual"
      },
      export_team_id: ENV["DEVELOPER_TEAM_ID"],
      xcargs: "DEVELOPMENT_TEAM=#{ENV["DEVELOPER_TEAM_ID"]}"
    )

    upload_to_testflight(
      username: ENV["APPLE_ID"],
      app_identifier: "com.cybage.alm"
    )
  end
end
