build_app(
  scheme: "Runner",
  export_method: "app-store",
  export_options: {
    provisioningProfiles: {
      "com.example.calculatorApp" => "CybageCI"
    },
    signingStyle: "manual",
    teamID: "
VB78Y67GX6" # Replace with your actual team ID
  },
  xcargs: "DEVELOPMENT_TEAM=
VB78Y67GX6",
)
